#Dummy update to kick off a build

language: java
jdk: oraclejdk7

before_install:
  # Gradle
  - wget http://services.gradle.org/distributions/gradle-1.6-bin.zip
  - unzip gradle-1.6-bin.zip
  - which gradle
  - export GRADLE_HOME=$PWD/gradle-1.6
  - export PATH=$GRADLE_HOME/bin:$PATH
  - which gradle

script: gradle assemble
